### ISSUE TITLE
Open the editor for a *.csv file gives NPE

### ISSUE THREAD

**Issue by axkr** [hallvard/etablesaw#1] opened 2020-02-15 10:49 UTC
I try opening the tabelsaw editor for the typical `tornadoes_1950-2014.csv` tablesaw file and getting this NPE:

```
java.lang.NullPointerException
	at etablesaw.ui.editor.ExprSupportHelper.applyExprs(ExprSupportHelper.java:42)
	at etablesaw.ui.editor.ExprSupportFilterStrategy.applyFilter(ExprSupportFilterStrategy.java:24)
	at org.eclipse.nebula.widgets.nattable.filterrow.FilterRowDataProvider.clearAllFilters(FilterRowDataProvider.java:323)
	at etablesaw.ui.editor.NatTablesawViewer.clearFilter(NatTablesawViewer.java:250)
	at etablesaw.ui.editor.NatTablesawViewer.setInput(NatTablesawViewer.java:95)
	at etablesaw.ui.editor.NatTablesawEditor.createPartControl(NatTablesawEditor.java:280)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:154)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:361)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1002)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:967)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:408)
```

![grafik](https://user-images.githubusercontent.com/3109793/74586568-2e3dd580-4fe9-11ea-8dcf-8fbe0a89732e.png)

**Comment by hallvard** [comment] 2020-02-15 23:02
The problem is that currently the xaw DSL is hardcoded as the expression language used for column filter, and if it's not present, you get a NPE. I've checked in a fix so 1) it removes the filter header  row it no expression language is found and 2) uses the first expression language it finds, so it's easy to replace with your own.

Oops, the above commit referenced the wrong issues, it should have been number 2...

**Closed as completed by hallvard** 2020-02-15 23:02 UTC
